apps:
  - name: backend
    script: 'npm run start:watch'
    cwd: backend
    instances: 1
    watch: false

  - name: questionnaire
    script: 'npm run start'
    cwd: questionnaire
    instances: 1
    watch: false

  - name: backoffice
    script: 'npm run start'
    cwd: backoffice
    instances: 1
    watch: false

  - name: widget
    script: 'npm run start'
    cwd: widget
    instances: 1
    watch: false

  - name: stats
    script: 'npm run start'
    cwd: stats
    instances: 1
    watch: false
