apps:
  - name: backend
    script: 'npm run start:watch'
    cwd: backend
    instances: 1
    watch: false

  - name: backoffice
    script: 'npm run start'
    cwd: backoffice
    instances: 1
    watch: false
