version: '3.3'
services:

  nginx:
    image: anotea_nginx
    container_name: anotea_nginx
    build:
      context: ./misc/nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - backoffice
      - questionnaire

  backoffice:
    image: anotea_backoffice
    container_name: anotea_backoffice
    build:
      context: backoffice
    depends_on:
      - backend

  questionnaire:
    image: anotea_questionnaire
    container_name: anotea_questionnaire
    build:
      context: questionnaire
    depends_on:
      - backend

  questionnaire:
    image: anotea_widget
    container_name: anotea_widget
    build:
      context: widget
      args:
        - ANOTEA_GOOGLE_ANALYTICS_ID=1234
        - ANOTEA_HOTJAR_ID=1234
    depends_on:
      - backend

  backend:
    image: anotea_backend
    container_name: anotea_backend
    build:
      context: backend
    depends_on:
      - mongodb
      - smtp
