version: '3.3'
services:

  nginx:
    image: anotea_nginx
    container_name: anotea_nginx
    build:
      context: ./misc/nginx
    ports:
    - 80:80
    volumes:
    - ./.data/nginx:/var/log/nginx:rw
    depends_on:
    - backend
    - backoffice

  backoffice:
    image: anotea_backoffice
    container_name: anotea_backoffice
    build:
      context: backoffice
    depends_on:
    - backend

  backend:
    image: anotea_backend
    container_name: anotea_backend
    build:
      context: backend
    environment:
    - ANOTEA_MONGODB_URI=mongodb://mongodb:27017/anotea?w=1
    - ANOTEA_REDIS_HOST=redis
    - ANOTEA_REDIS_PORT=6379
    - ANOTEA_SMTP_HOST=smtp
    - ANOTEA_SMTP_PORT=25
    depends_on:
    - mongodb
    - redis
    - smtp
