# This file is for dev only and is ignored on other environments.
# It can be overridden locally by creating a file named docker-compose.local.yml

version: '3.3'
services:

  backend:
    command: npm run start:watch
    volumes:
      - ./backend:/opt/anotea/backend:ro
    environment:
      - ANOTEA_LOG_JSON=true
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.backend
    depends_on:
      - fluentbit

  backoffice:
    working_dir: /opt/anotea/backoffice
    command: npm start
    volumes:
      - ./backoffice:/opt/anotea/backoffice:ro

  mongodb:
    image: mongo:4.0.4-xenial
    container_name: anotea_mongodb
    command: --wiredTigerCacheSizeGB 1
    volumes:
      - ./.data/mongodb/db:/data/db
      - ./.data/mongodb/config:/data/configdb
      - ./.data/backups/mongodb:/data/backups
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.mongodb
    depends_on:
      - fluentbit

  smtp:
    image: mailhog/mailhog
    container_name: anotea_smtp
    ports:
      - 8024:8025
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.smtp
    depends_on:
      - fluentbit

  ###########
  #EFK stack
  ##########

  fluentbit:
    image: anotea_fluentbit
    container_name: anotea_fluentbit
    build:
      context: misc/efk/fluentbit
    ports:
      - "24224:24224"
    environment:
      - ANOTEA_FLUENTBIT_ELASTICSEARCH_HOST=elasticsearch
      - ANOTEA_FLUENTBIT_ELASTICSEARCH_PORT=9200
      - ANOTEA_FLUENTBIT_ELASTICSEARCH_TLS=false
      - ANOTEA_FLUENTBIT_ELASTICSEARCH_USER=
      - ANOTEA_FLUENTBIT_ELASTICSEARCH_PASSWORD=
    depends_on:
      - elasticsearch

  elasticsearch:
    image: anotea_elasticsearch
    container_name: anotea_elasticsearch
    build:
      context: misc/efk/elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: anotea_kibana
    container_name: anotea_kibana
    build:
      context: misc/efk/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

